In [13]:
import numpy as np
import pandas as pd

In [14]:
data=pd.read_excel("indian_employee_data_50.xlsx")

In [16]:
data.head()

,Emp_ID,Name,Age,Salary (INR),Experience (Years),City,Department,Performance Rating
0,101,Amit Sharma,27,650000.0,4.0,Delhi,IT,4.5
1,102,Riya Gupta,32,NaN,8.0,Mumbai,HR,3.8
2,103,Rajesh Verma,45,1200000.0,inf,Bangalore,Finance,4.9
3,104,Priya Singh,29,720000.0,6.0,Kolkata,IT,4.2
4,105,Sunil Kumar,26,500000.0,3.0,Chennai,Sales,NaN

In [17]:
data.tail()

,Emp_ID,Name,Age,Salary (INR),Experience (Years),City,Department,Performance Rating
45,146,Naveen Kumar,27,580000.0,3.0,Bangalore,IT,3.9
46,147,Rakesh Meena,41,1450000.0,18.0,Jaipur,Management,4.7
47,148,Divya Rao,35,910000.0,10.0,Mysore,Finance,4.2
48,149,Siddharth Jain,29,680000.0,5.0,Udaipur,Marketing,3.8
49,150,Anita Paul,46,2200000.0,24.0,Kolkata,Operations,4.8

In [15]:
data.isnull().sum()

Emp_ID                0
Name                  0
Age                   0
Salary (INR)          2
Experience (Years)    0
City                  0
Department            0
Performance Rating    1
dtype: int64

In [4]:
data["Salary (INR)"].fillna(data["Salary (INR)"].mean(), inplace=True)
data["Performance Rating"].fillna(data["Performance Rating"].median(), inplace=True)

In [5]:
data.isnull().sum()

Emp_ID                0
Name                  0
Age                   0
Salary (INR)          0
Experience (Years)    0
City                  0
Department            0
Performance Rating    0
dtype: int64

In [6]:
data.replace([np.inf,-np.inf],np.nan,inplace=True)

In [7]:
data.fillna(data.mean(numeric_only=True), inplace=True)

In [8]:
data.drop_duplicates(inplace=True)

In [9]:
#replace negative Salaries
data["Salary (INR)"] =np.where(data["Salary (INR)"]< 0,data["Salary (INR)"].mean(),data["Salary (INR)"])

In [10]:
salary_mean=data["Salary (INR)"].mean()
salary_std=data["Salary (INR)"].std()

lower_bound=salary_mean-(3*salary_std)
upper_bound=salary_mean+(3*salary_std)

In [11]:
# removing rows where salary is too high or too low
data = data[(data["Salary (INR)"] >=lower_bound) & (data["Salary (INR)"] <=upper_bound)]

In [12]:
data.to_csv("new dataset" ,index=True)
print(data)

    Emp_ID               Name  Age  Salary (INR)  Experience (Years)  \
0      101        Amit Sharma   27  6.500000e+05            4.000000
1      102         Riya Gupta   32  1.222717e+06            8.000000
2      103       Rajesh Verma   45  1.200000e+06           11.734694
3      104        Priya Singh   29  7.200000e+05            6.000000
4      105        Sunil Kumar   26  5.000000e+05            3.000000
5      106         Alok Mehta   52  2.000000e+06           28.000000
6      107       Kavita Yadav   31  1.222717e+06           10.000000
7      108      Pankaj Mishra   24  1.222717e+06            2.000000
8      109      Deepika Reddy   48  3.000000e+06           30.000000
9      110       Ramesh Patil   29  7.200000e+05            6.000000
10     111         Meera Nair   34  8.200000e+05            9.000000
11     112       Sameer Desai   37  1.100000e+06           15.000000
12     113        Swati Joshi   29  6.500000e+05            5.000000
14     115      Anjali Saxena   23  3.800000e+05            1.000000
15     116      Manish Khanna   40  1.250000e+06           18.000000
16     117       Arjun Pandey   31  7.500000e+05            7.000000
17     118        Neha Kapoor   28  1.222717e+06            4.000000
18     119          Amit Shah   36  9.800000e+05           12.000000
19     120       Rohit Bansal   42  1.222717e+06           20.000000
20     121       Sneha Tiwari   25  5.500000e+05            2.000000
22     123      Preeti Sharma   33  7.700000e+05            8.000000
23     124      Aditya Saxena   22  1.222717e+06            0.000000
24     125        Rahul Reddy   30  8.500000e+05            5.000000
25     126        Nikita Jain   27  6.000000e+05            3.000000
26     127     Karan Malhotra   41  1.400000e+06           17.000000
27     128     Pooja Kulkarni   35  9.200000e+05           11.000000
28     129          Anand Rao   50  2.600000e+06           27.000000
29     130       Shilpa Menon   28  6.100000e+05            4.000000
30     131       Varun Chawla   39  1.150000e+06           14.000000
31     132       Ritu Agarwal   31  7.800000e+05            7.000000
32     133       Sachin Yadav   26  4.800000e+05            2.000000
33     134         Mehul Shah   44  1.700000e+06           19.000000
34     135        Nandini Rao   29  6.900000e+05            5.000000
35     136       Prakash Iyer   53  3.100000e+06           30.000000
36     137     Tanvi Kulkarni   24  4.200000e+05            1.000000
37     138        Vikas Singh   38  1.050000e+06           13.000000
38     139        Harish Nair   47  2.100000e+06           25.000000
39     140        Ayesha Khan   34  8.900000e+05            9.000000
40     141       Rohini Patil   28  6.300000e+05            4.000000
41     142        Akash Verma   36  9.800000e+05           11.000000
42     143        Suman Ghosh   45  1.600000e+06           21.000000
43     144      Iqbal Hussain   39  1.350000e+06           16.000000
44     145  Pallavi Deshpande   31  7.600000e+05            6.000000
45     146       Naveen Kumar   27  5.800000e+05            3.000000
46     147       Rakesh Meena   41  1.450000e+06           18.000000
47     148          Divya Rao   35  9.100000e+05           10.000000
48     149     Siddharth Jain   29  6.800000e+05            5.000000
49     150         Anita Paul   46  2.200000e+06           24.000000

          City  Department  Performance Rating
0        Delhi          IT                 4.5
1       Mumbai          HR                 3.8
2    Bangalore     Finance                 4.9
3      Kolkata          IT                 4.2
4      Chennai       Sales                 4.3
5    Hyderabad  Operations                 5.0
6         Pune          IT                 4.0
7       Jaipur   Marketing                 3.5
8    Bangalore  Management                 5.0
9      Kolkata          IT                 4.2
10       Kochi          HR                 4.3
11       Delhi     Finance                 4.8
12      Mumbai          IT                 4.6
14        Pune          HR                 3.9
15   Hyderabad  Operations                 4.7
16      Jaipur          IT                 4.4
17   Bangalore          IT                 3.8
18      Mumbai     Finance                 4.9
19   Hyderabad  Operations                 4.5
20     Kolkata       Sales                 3.6
22        Pune          HR                 4.1
23       Delhi          IT                 3.2
24      Mumbai          IT                 4.5
25      Jaipur   Marketing                 3.9
26       Delhi     Finance                 4.6
27        Pune          HR                 4.2
28   Bangalore  Operations                 4.8
29       Kochi          IT                 4.0
30  Chandigarh     Finance                 4.4
31       Delhi          HR                 4.1
32       Noida       Sales                 3.7
33   Ahmedabad  Operations                 4.6
34   Bangalore          IT                 4.3
35     Chennai  Management                 5.0
36        Pune          HR                 3.5
37     Lucknow     Finance                 4.2
38       Kochi  Operations                 4.7
39      Mumbai   Marketing                 4.1
40        Pune          IT                 4.0
41      Indore          IT                 4.3
42     Kolkata     Finance                 4.6
43   Hyderabad  Operations                 4.4
44      Nagpur          HR                 4.0
45   Bangalore          IT                 3.9
46      Jaipur  Management                 4.7
47      Mysore     Finance                 4.2
48     Udaipur   Marketing                 3.8
49     Kolkata  Operations                 4.8